### ISSUE TITLE
strange test behaviour after update attempt from 0.9.2 to 1.0.1

### ISSUE THREAD

**Issue by abatko** [blowmage/minitest-rails#159]
First and foremost, thank you for this great gem. I am sorry to bother you.

Prior to updating I ran the whole test suite as follows (as I always do), and everything passed:

    bundle exec rake minitest:all RAILS_ENV=test

After updating I got 3 Failures and 1 Error using the same command. All 4 issues correspond to the same thing: in one of my models I have a `before_validation` that includes a line like this:

    unless Money::Currency.find(price_currency)

In all 4 cases, it returns `nil`, whereas it is supposed to find the given `price_currency`.

**However**, when I run the tests like any of the following they **pass**:

    bundle exec ruby -I test test/helpers/foo_helper_test.rb
    bundle exec ruby -I test test/helpers/foo_helper_test.rb -n test__particular_test

    bundle exec ruby -I test test/models/foo_test.rb
    bundle exec ruby -I test test/models/foo_test.rb -n test_particular_test

Also, I am also able to successfully run `Money::Currency.find('cad')` at the `rails console`.

How can this be?

*Note that I also simultaneously updated `minitest-rails-capybara` from `0.10.0` to `1.0.0`.*

**Comment by blowmage** [comment]
Closing until someone can help me reproduce.
