### ISSUE TITLE
"Unable to resolve controller" when nesting describe blocks in native rails controller test class

### ISSUE THREAD

**Issue by henrypoydar** [blowmage/minitest-rails#165]
This controller test will throw the "Unable to resolve controller" error:

```
class ArticlesControllerTest < ActionController::TestCase
  describe 'GET #index' do
    setup { get :index }
    it "does x" do
      assert true
    end
    it "does y" do
      assert true
    end
  end
end
```

This code will not:

```
describe ArticlesController do
  describe 'GET #index' do
    setup { get :index }
    it "does x" do
      assert true
    end
    it "does y" do
      assert true
    end
  end
end
```

The first example works when requiring `minitest/spec` without the gem. Simple workaround is to stick with the DSL (or not).

**Comment by zenspider** [comment]
The second example is not syntactically correct ruby. Line 1 needs a `do`.

**Comment by hpoydar** [comment]
Got it. Fixed.

**Comment by chrisortman** [comment]
I think the problem is because when minitest runs the describe block the stack is empty (since this is your first describe call) and now when mintiest-rails tries to figure out the controller the original classname from the test is lost.

mintiest-spec-rails gets around this by overriding the describe method and pushing self onto the stack.

**Comment by blowmage** [comment]
Good catch. That sounds plausible. I'll run some tests and see if I can get this edge case resolved.

**Comment by blowmage** [comment]
Good catch. That sounds plausible. I'll run some tests and see if I can get this edge case resolved.

**Comment by traels** [comment]
I am having the same problem but if i do the following it will work in those cases where it starts with the it will work test. So I can get it to only fail 50% of the times :(

```ruby
class ArticlesControllerTest < ActionController::TestCase
  it 'will work' do
  end
  describe 'GET #index' do
    setup { get :index }
    it "does x" do
      assert true
    end
    it "does y" do
      assert true
    end
  end
end
```

**Comment by metaskills** [comment]
I solved this for Rails 3.0 and 3.1 in the mintiest-spec-rails gem the other day. Not sure if the version match for anyones issue, but thought I would share. This is in our 3-x-stable branch. https://github.com/metaskills/minitest-spec-rails/commit/f1e82dced915020683385dae396b13347739645b

**Comment by grosser** [comment]
FYI posted monkeypatch in https://github.com/blowmage/minitest-rails/issues/195 to fix it ...

**Comment by blowmage** [comment]
We aren't going to support controller tests using the spec DSL from rails 5.0 forward. You are better off upgrading your controller tests to use IntegrationTest.
