### ISSUE TITLE
In Rails engine, NoMethodError <fixtures-name> when trying to access fixtures

### ISSUE THREAD

**Issue by bikramwp** [blowmage/minitest-rails#167]
Hi,
  
I am trying to test a Rails engine with minitest-rails but am not able to use fixtures in my
test cases. (tried on rails 4.1/4.2 and minitest-rails 2.1.1; not using rspec at all)

Without minitest-rails, fixtures work:

```ruby
require 'test_helper'
module Foo
  class CustomerTest < ActiveSupport::TestCase
    test "alex is id 5" do
      assert foo_customers(:alex).id, 5
    end
  end
end
```

With minitest-rails, I get error
```ruby
require 'test_helper'
module Foo
  describe Customer do
    let(:alex) {foo_customers(:alex) } # error here
    test "alex is id 5" do
      assert alex.id, 5
    end
  end
end
```
Error is:
```
NoMethodError: undefined method `foo_customers' for #<#<Class:0x007f07822daee8>:0x007f07820224a8>
```

**Comment by bikramwp** [comment]
PS. I am not using rspec

**Comment by blowmage** [comment]
Can you copy/paste your `test/test_helper.rb` file? This looks to me that `minitest/rails` isn't getting required properly. It should be required after `rails/test_help`.

FWIW, you can test that the spec DSL is resolving your constants correctly by adding a test like this one:

```ruby
module Foo
  describe Customer do
    it "uses the right test class" do
      self.class.ancestors.must_include ActiveSupport::TestCase
    end
  end
end
```

**Comment by bikramwp** [comment]
Thanks for looking into this. The `test/test_helper.rb` is below:
(just a reminder that this is inside a Rails engine, not an app; in case that makes a difference)
(also, I am running tests with `rake test`)

```ruby
ENV["RAILS_ENV"] = "test"

# NOTE: === the only difference from the one created by rails generate minitest:install
# is the path was changed to "../../test/dummy/config/environment" 
require File.expand_path("../../test/dummy/config/environment", __FILE__)

require "rails/test_help"
require "minitest/rails"

# To add Capybara feature tests add `gem "minitest-rails-capybara"`
# to the test group in the Gemfile and uncomment the following:
# require "minitest/rails/capybara"

# Uncomment for awesome colorful output
# require "minitest/pride"

class ActiveSupport::TestCase
    ActiveRecord::Migration.check_pending!

    # Setup all fixtures in test/fixtures/*.(yml|csv) for all tests in alphabetical order.
  #
  # Note: You'll currently still have to declare fixtures explicitly in integration tests
  # -- they do not yet inherit this setting
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

**Comment by blowmage** [comment]
Are you sure the fixtures work when using test-style? Here is the `test_helper.rb` that I have in order to use fixtures and routes in my engine tests. The only change between using the spec DSL or not is the require for `minitest/rails`.

```ruby
# Configure Rails Environment
ENV["RAILS_ENV"] = "test"

require File.expand_path("../../test/dummy/config/environment.rb",  __FILE__)
ActiveRecord::Migrator.migrations_paths = [File.expand_path("../../test/dummy/db/migrate", __FILE__)]
ActiveRecord::Migrator.migrations_paths << File.expand_path('../../db/migrate', __FILE__)
require "rails/test_help"
require "minitest/rails"

# Filter out Minitest backtrace while allowing backtrace from other libraries
# to be shown.
Minitest.backtrace_filter = Minitest::BacktraceFilter.new

# Load support files
Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].each { |f| require f }

# Load fixtures from the engine
if ActiveSupport::TestCase.respond_to?(:fixture_path=)
  ActiveSupport::TestCase.fixture_path = File.expand_path("../fixtures", __FILE__)
end

class ActiveSupport::TestCase
  fixtures :all
end

class ActionController::TestCase
  setup do
    @routes = Foo::Engine.routes
  end
end
```

If I comment out the line that sets the `fixture_path` I will get the `NoMethodError: undefined method 'named_route'` error, in both my test-style and spec-style tests.

**Comment by bikramwp** [comment]
I looked into this again and created a test repo [minitesttestrepo1](https://github.com/bikramwp/minitesttestrepo1/commits/master)
It appears that I need a reboot, because that repo is testing fine now (but was not working in a previous similar test repo I had made)

I'll close this issue.
Thanks a lot and apologies for wasting your time on this :/

**Comment by blowmage** [comment]
No problem and no waste of time. :) I bet this issue is found and helps someone in the future.
