### ISSUE TITLE
problem upgrading to 2.1.1

### ISSUE THREAD

**Issue by abatko** [blowmage/minitest-rails#170]
**Gemfile**

    -gem 'rails', '4.0.13'
    +gem 'rails', '4.1.0'
 
     group :test, :development do
    -       gem 'minitest-rails', '~> 1.0.1'
    +       gem 'minitest-rails', '~> 2.1.1'
            gem 'factory_girl_rails', '~> 4.5.0'
     end
  
     group :test do
    -       gem 'minitest-rails-capybara', '~> 1.0.0'
    +       gem 'minitest-rails-capybara', '~> 2.1.1'
     end

Note: Running `bundle` brings `minitest` from version `4.7.5` to `5.5.1`.

**rake test**

    -bash> bundle exec rake test
    rake aborted!
    NameError: uninitialized constant MiniTest
    /Volumes/.../Users/.../.../lib/tasks/factories_first.rake:1:in `<top (required)>'

**lib/tasks/factories_first.rake**

    MiniTest::Rails::Testing.default_tasks.unshift('aaa_factories_tests') if Rails.env =~ /^(development|test)\z/

When I comment out the line cited in `factories_first.rake` and re-run the tests the error becomes:

    /Users/.../.rvm/gems/ruby-2.0.0-p598@.../gems/minitest-5.5.1/lib/minitest.rb:510:in `+': nil can't be coerced into Fixnum (TypeError)

It seems my tests are not seen or executed - I placed a conditional at `minitest.rb:510` and `minitest.rb:356` to avoid these `nil` errors, and then the suite runs without executing an assertion. Example: `12 runs, 0 assertions, 0 failures, 0 errors, 0 skips`

Could you kindly suggest something for me to try to resolve this?

**Comment by abatko** [comment]
I narrowed it down to this custom `teardown` method in `test/test_helper.rb`. Commenting out this method resolves the problem. This was not a problem until upgrading from `minitest-rails` `1.0.1` to `2.1.1` - but to be fair I am not sure that the method serves a meaningful purpose (and it has also given me trouble in the past: [https://github.com/seattlerb/minitest/issues/363](https://github.com/seattlerb/minitest/issues/363))
```
class ActiveSupport::TestCase
        # Set all unnecessary instance variables to nil after every test
        def teardown
                @@reserved_ivars = [ :@_assertions, :@fixture_connections ]
                (instance_variables - @@reserved_ivars).each do |ivar|
                        instance_variable_set(ivar, nil)
                end
        end
end
```

**Comment by zenspider** [comment]
No, that method never served a meaningful purpose.
