### ISSUE TITLE
run all tests against clean database after upgrade to 2.1.1

### ISSUE THREAD

**Issue by abatko** [blowmage/minitest-rails#171]
What configuration is necessary in order to be able to run each and every test against a clean test database?

I keep seeing random behaviour (I believe tests run in random order - which is great), but I have been able to run the whole test suite successfully **only once**... otherwise there are failures and errors here and there due to an unclean test database (conflicting data). I thought all transactions are rolled back after each and every test, yet when I look into my test database after any given run there is a pileup of test relics.

I have tried many combinations of `bundle exec rake test:all` and `bundle exec rake test:all:db` with the following:
 * with and without `database_cleaner` (though I am of the understanding that `database_cleaner` is unnecessary because all transactions are supposed to be rolled back)
 * with and without `ActiveRecord::Migration.maintain_test_schema!` (the new `rails 4.1` feature)
 * with and without first running the deprecated `rake db:test:prepare`

**Comment by blowmage** [comment]
Sounds like your tests may be updating the database outside the test's database transaction. Are you using the spec DSL? Do you have models that don't inherit from ActiveRecord?

**Comment by abatko** [comment]
Thanks for your response.

I manually bisected to narrow the problem down to my policy tests.

**test/policies/user_policy_test.rb:**
```
require 'test_helper'
class UserPolicyTest < Minitest::Test
        def test_create
            assert true
        end
end
```

This was not a problem prior to this upgrade. Should I be subclassing from something other than `Minitest::Test`?

At https://github.com/seattlerb/minitest I keep seeing `require "minitest/autorun"` at the top of most test files... I don't know what it's for (I don't understand "*the easy and explicit way to run all your tests*" - all my tests already run via `rake test:all`).

**Comment by blowmage** [comment]
Any test that accesses or manipulates the database needs to inherit from ActiveSupport::TestCase, where the database transaction happens.

**Comment by abatko** [comment]
Thanks a lot! Inheriting from `ActiveSupport::TestCase` did the trick.
