### ISSUE TITLE
check_pending! vs maintain_test_schema!

### ISSUE THREAD

**Issue by abatko** [blowmage/minitest-rails#173]
I ran `rails generate minitest:install` on a new Rails 4.1 / Minitest 2.1.1 app, just to see the content of the generated `test/test_helper.rb`:

```
ENV["RAILS_ENV"] = "test"
require File.expand_path("../../config/environment", __FILE__)
require "rails/test_help"
require "minitest/rails"

# To add Capybara feature tests add `gem "minitest-rails-capybara"`
# to the test group in the Gemfile and uncomment the following:
# require "minitest/rails/capybara"

# Uncomment for awesome colorful output
# require "minitest/pride"

class ActiveSupport::TestCase
    ActiveRecord::Migration.check_pending!

    # Setup all fixtures in test/fixtures/*.(yml|csv) for all tests in alphabetical order.
  #
  # Note: You'll currently still have to declare fixtures explicitly in integration tests
  # -- they do not yet inherit this setting
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

Note the line `ActiveRecord::Migration.check_pending!`

I happened to come across [an rspec-rails PR](https://github.com/rspec/rspec-rails/pull/946/files) that instead calls the following for Rails >= `4.1`...

```
ActiveRecord::Migration.maintain_test_schema!
```

...and I am just wondering if we should do the same for minitest-rails.

You can read a related conversation here: https://github.com/rails/rails/pull/13528

**Comment by natebird** [comment]
Looking at the pull request it seems that requiring `rails/test_help` will maintain the test schema automatically. This means that it should be safe to remove the `ActiveRecord::Migration.check_pending!` line.
