### ISSUE TITLE
minitest-rails in Gemfile

### ISSUE THREAD

**Issue by abatko** [blowmage/minitest-rails#174]
It used to be the case that we had to add `minitest-rails` to `Gemfile`, in the `:development` group, but that was because there were `minitest` `rake` tasks (as of `2.0.0` they have been removed) - so I am wondering if there is any purpose to still including `minitest-rails` in the `:development` group of `Gemfile` as opposed to just the `:test` group.

**Comment by blowmage** [comment]
As of 1.0 the guidance given is to not put it in a group.

**Comment by abatko** [comment]
What is the reasoning for this guidance?

My worry is unnecessarily polluting `development`, let alone `production`.

Have you come across http://blog.testdouble.com/posts/2015-02-16-arcane-knowledge.html ? -- see point # 3.

**Comment by blowmage** [comment]
> What is the reasoning for this guidance?

Because that is the guidance.

> My worry is unnecessarily polluting `development`, let alone `production`.

It doesn't.

> Have you come across http://blog.testdouble.com/posts/2015-02-16-arcane-knowledge.html ? -- see point # 3.

He is [wrong](https://twitter.com/blowmage/status/568162202248544256).

**Comment by metaskills** [comment]
@blowmage There are quite a few things on that list that I do not like either from personal Minitest usage along with mintiest-spec-rails too.

**Comment by lgs** [comment]
@metaskills 

... can you please argue your point for the "the rest of us" poor man's testers ? (-: :-)

**Comment by blowmage** [comment]
Closing as this seems to be answered.
