### ISSUE TITLE
configuration questions wrt ENV['RAILS_ENV'] and Rails.env

### ISSUE THREAD

**Issue by abatko** [blowmage/minitest-rails#175]
Running `rails generate minitest:install` produces `test/test_helper.rb` with `ENV["RAILS_ENV"] = "test"` at the top, yet if I comment out that line, and instead `puts` that and other related variables, it is already set to `test` when I run `bundle exec rake test`, `bundle exec rake test:all`, and `bundle exec rake test:all:db`. So what is the point of this line?
```
puts "--- Rails.env: #{Rails.env}, ENV['RAILS_ENV']: #{ENV['RAILS_ENV']}, ENV['RACK_ENV']: #{ENV['RACK_ENV']}"
#ENV['RAILS_ENV'] = 'test'
```

More importantly, `Rails.env` is still set to `development` as opposed to `test`, and the fix for this, which is missing from the `README`, seems to be to add the following line to `config/application.rb`:
```
require 'minitest/rails/railtie'
```
Is the above remedy correct?

**Comment by zenspider** [comment]
> On Feb 25, 2015, at 14:59, Alex Batko <notifications@github.com> wrote:
> 
> Running rails generate minitest:install produces test/test_helper.rb with ENV["RAILS_ENV"] = "test" at the top, yet if I comment out that line, and instead puts that and other related variables, it is already set to test when I run bundle exec rake test, bundle exec rake test:all, and bundle exec rake test:all:db. So what is the point of this line?

ruby -Ilib:test test/some_test.rb

**Comment by abatko** [comment]
Thanks.

I have also noticed that it is possible to just do:
```
ruby -I test test/some_test.rb
```
(i.e. to not have to type `lib:`)

**Comment by blowmage** [comment]
Compare to the [default `test/test_helper.rb`](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/test/test_helper.rb).

**Comment by abatko** [comment]
Thanks.

And how about adding `require 'minitest/rails/railtie'` to `config/application.rb` as a remedy for setting `Rails.env` to `test`?

**Comment by abatko** [comment]
(And I suppose it would be a good thing to do anyway, wrt Spring? https://github.com/blowmage/minitest-rails/issues/139#issuecomment-44466134)

**Comment by blowmage** [comment]
We are going to maintain compatibility with the default test helper file. Closing.

**Comment by jamesbebbington** [comment]
Like @abatko, I was also wondering why the generator was explicitly setting the `Rails.env`.

@blowmage said:

> We are going to maintain compatibility with the default test helper file. Closing.

It now looks like, as of https://github.com/rails/rails/commit/9a80f52541ed2c93ebef02909ecab3aaf9127150, that the default test helper file is no longer doing this either, so perhaps time to revisit this?
