### ISSUE TITLE
rails generate minitest:install  or any other rails generate minitest:suchandsuch does not work!

### ISSUE THREAD

**Issue by lustremedia** [blowmage/minitest-rails#177]
```
~/ rails generate minitest:feature myfeature
Usage:
  rails new APP_PATH [options]
Options:
  -r, [--ruby=PATH]                                      # Path to the Ruby binary of your choice
...
```

Gemfile:

```
gem 'minitest-rails'

group :test do
  gem 'minitest-rails-capybara'
end
```

How do I need to call ```rails generate minitest:<>```  ?

**Comment by lustremedia** [comment]
Ok I created a brand new project and followed the instructions and it worked. The issue must be with my particular project then. Any hints on how to debug that?

Test run ok, but I can't use generators such as ```minitest:feature```

**Comment by lustremedia** [comment]
Turned out that my rails/bin directory was missing!

**Comment by blowmage** [comment]
Haven't had time to look into it. Glad you got it solved!

**Comment by lustremedia** [comment]
np! Thank you!
