### ISSUE TITLE
Rebase the rails5 branch against master

### ISSUE THREAD

**Issue by pwnall** [blowmage/minitest-rails#182]
I'm using the `rails5` branch, and I noticed that it's a bit stale. I did a rebase. If you'd like to avoid wasting 10-15 minutes handling conflicts, you can use my work here.
https://github.com/pwnall/minitest-rails/tree/rails5

I hope this helps!

**Comment by jlecour** [comment]
Hi,

Is there anything that we can do to help finish this issue?

Thanks to maintainers and contributors for the great work .

**Comment by blowmage** [comment]
The `rails5` branch is updated. It is now the same as `master`. It would be a good idea to switch your references to `master` as the `rails5` branch may lag master for a bit and will ultimately go away
