### ISSUE TITLE
The rails5 branch breaks with rails edge

### ISSUE THREAD

**Issue by pwnall** [blowmage/minitest-rails#183]
Some commit in rails added methods to the `Minitest` module that reference the `Rails` constant. When `minitest-rails` is loaded, the reference resolves to `Minitest::Rails`.

I submitted a PR to Rails that would fix this issue on the Rails side.
https://github.com/rails/rails/pull/20747

However, if that doesn't get resolved, it seems like the right solution would be to rename `Minitest::Rails`. Would you be interested in a contribution that accomplishes that?

**Comment by jonatack** [comment]
Thanks for that PR to Rails to fix the issue. Since the PR was merged, you could probably close this issue.

**Comment by blowmage** [comment]
The mintiest-rails master branch is now 3.0 and specific to rails5. This does not seem to be a problem using rails 3.0.0.rc1. Closing.
