### ISSUE TITLE
Rubocop

### ISSUE THREAD

**Issue by blowmage** [blowmage/minitest-rails#191]
Probably a good idea to enforce code style with rubocop so that those wanting to contribute don't violate the preferred code style accidentally...

**Comment by teoljungberg** [comment]
Have you thought about using https://houndci.com? It's free for open source projects!

(Disclaimer, I am one of the maintainers of Hound)

**Comment by blowmage** [comment]
Hi Teo. I have not. I'll look at it.

**Comment by SaiVardhan** [comment]
@blowmage Any plans on this.. :)

**Comment by blowmage** [comment]
This has been added in the Rails6 support.
