### ISSUE TITLE
Rails 5: Assert (no) tag error

### ISSUE THREAD

**Issue by ericboehs** [blowmage/minitest-rails#198]
Per https://github.com/rails/rails-dom-testing/commit/06adecc349381e906c481c3296045ba2dd8850e6, `assert_tag` and `assert_no_tag` have been "thrown out on the street".

Commenting it out here seemed to fix it: https://github.com/ericboehs/minitest-rails/commit/cdfaec6fd4300156e8f2290d0178af92015cf982.

I'm sure you'll want to do more than that though, so I haven't created a pull request.

**Comment by blowmage** [comment]
Great. Thanks for the heads up.

**Comment by mlt** [comment]
What one is supposed to use instead then? I would like to check node's content as well as sibling's content. No way?

**Comment by metaskills** [comment]
I use `assert_select` for almost anything in controller tests. It is quite versatile.

**Comment by mlt** [comment]
@metaskills CSS does not seem to be as expressive. I got by with a bunch of *nth-child* text asserts. It is just not as expressive and it is quite rigid... oh well.

**Comment by metaskills** [comment]
Cool, that's fine. Just wanted to help answer the question because I think that is the expectation. Also, IIRC, you can use XPath expressions too. But can't remember if that is only with Capybara or not. Cheers

**Comment by blowmage** [comment]
Closing as these assertions were removed in 3.0.0.
