### ISSUE TITLE
unable to use 'describe' block for controller with Devise

### ISSUE THREAD

**Issue by gpr** [blowmage/minitest-rails#200]
I'm not able to make the following test working:

```ruby
describe UsersController do
  include Devise::Test::ControllerHelpers

  before do
    sign_in create(:admin)
  end

  it 'gets index' do
    get users_url
    value(response).must_be :success?
  end
end
```

I get: 
```ruby
Minitest::UnexpectedError: NoMethodError: undefined method `env' for nil:NilClass
    devise (4.2.0) lib/devise/test/controller_helpers.rb:40:in `setup_controller_for_warden'`
```

This function is quite simple (see https://github.com/plataformatec/devise/blob/22784cb55abefc8a62c69dcc170a30d18e45c7ac/lib/devise/test/controller_helpers.rb#L39):
```ruby
     def setup_controller_for_warden #:nodoc:
        @request.env['action_controller.instance'] = @controller
      end
```

And the issue is that `@request` is `nil`.

Obviously I have no issue if I replace the `describe` block by  `class UsersControllerTest < ActionController::TestCase`.

An extract of my `Gemfile.lock`:
```Gemfile.lock
rails (5.0.0)
minitest-rails (3.0.0)
minitest (5.9.0)
devise (4.2.0)
```

**Comment by gpr** [comment]
That sounds obvious but I double checked; the following block does not work:

```
class UsersControllerTest < ActionDispatch::IntegrationTest
[...]
end
```

**Comment by gpr** [comment]
sorry wrong report, _Devise_ helpers does not work with `ActionDispatch::IntegrationTest`

**Comment by gpr** [comment]
Something changed between rails4 and rails5: here is the solution to make Devise working.

Add the following code to your `test_helper.rb`:
```
module ActionDispatch
  class IntegrationTest
    include Devise::Test::IntegrationHelpers
  end
end
```

**Comment by blowmage** [comment]
Glad you figured this out while I was sleeping! 😄
