### ISSUE TITLE
ActionView::Template::Error: nil is not a valid asset source

### ISSUE THREAD

**Issue by aldrienht** [blowmage/minitest-rails#201]
**I'm upgrading my Rails 4.2.6 to Rails 5.0.0.1**

Some of my previous controller codes are not working. One error I got is Template error.
Here is my simple test,

` test "should get index" do`
`     get :index`
`     assert_not_nil assigns(:users)`
`     assert_response :success`
`end`

I tried to set blank parameters like,
`     get :index, params: {}`

But still getting template error.

**Please help how can I fixed it in Rails 5 Minitest**

**Comment by blowmage** [comment]
https://stackoverflow.com/questions/37530024/rails-5-nil-is-not-a-valid-asset-source
