### ISSUE TITLE
plugin_rails_options.rb uninitialized constant Minitest::Rails::TestUnit

### ISSUE THREAD

**Issue by atstockland** [blowmage/minitest-rails#209]
I suspect this is caused in minitest-rails...but, I'm not positive.  For me this occurred only after upgrading to rails 5.2 (ruby 2.3.3).  Sorry, to be vague...but, I don't have much else to offer at this point.  

/gems/railties-5.2.0.beta2/lib/minitest/rails_plugin.rb:16:in `plugin_rails_options': uninitialized constant Minitest::Rails::TestUnit (NameError)

**Comment by lostapathy** [comment]
Related issue: rails/rails#31324

**Comment by ohammersmith** [comment]
The resolution of that Rails issue was to remove `minitest-rails` and/or `minitest-rails-capybara`.

Are there any plans to address this as a Rails 5.2 compatibility issue w/ `minitest-rails`?

**Comment by djensenius** [comment]
I am also interested to know if this will be updated.

**Comment by taq** [comment]
Just provided traceback information there. The commit who introduced that iine is [this one](https://github.com/rails/rails/commit/47308ff32a869f493ca85f7c5a58a082c084f391). Seems something related to `attach_before_load_options` that needs to be done by `minitest-rails`?

**Comment by taq** [comment]
If we implement the classes and needed method on, say, `railtie.rb`, for example:

```ruby
module Minitest
  module Rails
    module TestUnit
      class Runner
        def self.attach_before_load_options(*opts)
        end
      end
    end

    class Railtie < ::Rails::Railtie
    ...
```

it works, but this is just a cheap fix. I think the point is if `minitest-rails` or `minitest` should implement those classes and methods to be called for the Rails 5.2 or even if Rails 5.2 way to call that row on the commit I show above is wrong.

**Comment by marktellez** [comment]
I still get this problem

* rails 5.2.0 
* minitest-rails 3.0.0

**Comment by blowmage** [comment]
The issue was due to constant lookup and has been fixed in Rails. Here is the Rails issue: rails/rails#31324
