### ISSUE TITLE
Unable to run single test in RubyMine with apostrophe in its name

### ISSUE THREAD

**Issue by annamatveev** [blowmage/minitest-rails#210]
Hey,
When I try to run a test which has an apostrophe in its name, it says the test suite is empty. It happens only when you try to run a single test.

For example -
![image](https://user-images.githubusercontent.com/5776720/41837816-4551ec9e-7867-11e8-9f6d-d65541a863e4.png)

returns 

![image](https://user-images.githubusercontent.com/5776720/41837826-4e3a34f6-7867-11e8-82b6-2e80c9db6635.png)

I'm using minitest-rails 2.0 as I'm using Rails 4 in my app.

**Comment by blowmage** [comment]
I doubt this is due to something in minitest-rails.
