### ISSUE TITLE
Upgrading from 3.0.0 to 5.2.0 (and 6.0.0) causes fixtures to not be recreated after every test case

### ISSUE THREAD

**Issue by yawhide** [blowmage/minitest-rails#222]
Hello,

I am experiencing a weird issue when trying to upgrade from 3.0.0 to either 5.2.0 or 6.0.0. It seems my fixture (I only have one) gets created at the beginning of the test suite and then never gets re-created after each test case that is ran. My test cases work fine in 3.0.0, then i run `bundle update minitest-rails` to get 5.2.0 or `bundle update minitest-rails rails` to get minitest-rails 6.0.0. I then run `bundle exec rails test` and a few tests fail because some rows/fixtures are missing from the test database.

### Problem
Fixtures are not being re-created after every test case.
Any test cases that delete a row from the database are destroyed for the rest of the test suite.

### Expected behaviour
![image](https://user-images.githubusercontent.com/5014112/68401969-98242480-0148-11ea-85e2-9d2b9aab23d3.png)
https://api.rubyonrails.org/v5.2.3/classes/ActiveRecord/FixtureSet.html

Fixtures are re-created at the beginning of each test case.

### Extra info

My `test_helper.rb` is pretty simple:
```
# frozen_string_literal: true

ENV["RAILS_ENV"] ||= "test"

require_relative "../config/environment"
require "rails/test_help"
require "minitest/rails"
require "mocha/minitest"
require "webmock/minitest"

class Module
  include Minitest::Spec::DSL
end

class ActiveSupport::TestCase
  # Setup fixtures in test/fixtures/*.yml for all tests
  fixtures :all
  # Add more helper methods to be used by all tests here...
end
```

any ideas how to debug this?

**Comment by blowmage** [comment]
I'm not able to reproduce this behavior. What database are you using?

Neither 3.0 or 5.2 (or 6.0) change how rails handles fixtures, so I don't see how minitest-rails would affect this.

I would start with a very simple reproduction. If you aren't able to reproduce, I would start adding your other testing dependencies one at a time until you  are able to reproduce.

**Comment by yawhide** [comment]
> I'm not able to reproduce this behavior. What database are you using?
> 
> Neither 3.0 or 5.2 (or 6.0) change how rails handles fixtures, so I don't see how minitest-rails would affect this.
> 
> I would start with a very simple reproduction. If you aren't able to reproduce, I would start adding your other testing dependencies one at a time until you are able to reproduce.

good idea, let me try that. i am using mysql
