### ISSUE TITLE
Rails 6.1.x support

### ISSUE THREAD

**Issue by jasonrudolph** [blowmage/minitest-rails#226]
[Rails 6.1.0 RC1 is out](https://weblog.rubyonrails.org/2020/11/2/Rails-6-1-rc1-release/), and it would be awesome to be able to continue using minitest-rails with Rails 6.1. The README indicates that supporting Rails 6.1 would involve a newer version of minitest-rails:

https://github.com/blowmage/minitest-rails/blob/8927079974b55ef84f5e3fa08d5ed54979c003f8/README.md#L22-L28

If it would be helpful to have a pull request for this, I'm happy to give it a shot. :-)

**Comment by blowmage** [comment]
See #227.

**Comment by srini91** [comment]
Rails 6.1 released today; any chance minitest-rails could support?

**Comment by jasonrudolph** [comment]
Closed in #228. Thanks, @blowmage! Thanks, @asgerb!
