### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by vitaly** [blowmage/minitest-rails#231]
Can you please specify what this gem does above what Rails already provides with it 's Minitest support, which is standard in Rails since long time ago?

**Comment by blowmage** [comment]
The gem's feature set has changed as Rails has changed how it uses Minitest over time. Currently it adds support for using the Minitest Spec DSL in Rails tests, adds support for more expected assertion names (`refute_change` vs. `assert_no_change`), alternate test generator templates for spec/test styles, etc...

This [blog post](https://blowmage.com/2019/06/18/minitest-rails-releases) may help, but it also may not.
