### ISSUE TITLE
Rails 7.0 support

### ISSUE THREAD

**Issue by skateman** [blowmage/minitest-rails#234]
Rails 7.0 is [out](https://rubyonrails.org/2021/12/15/Rails-7-fulfilling-a-vision), are there any plans to support it in this gem? :pray:

**Comment by kangkyu** [comment]
#232 resolved this issue. But rails 7.0.1 just came out https://rubygems.org/gems/rails/versions/7.0.1

**Comment by skateman** [comment]
We would still need to bump the gem to make this work :confused:

**Comment by shawndeprey** [comment]
@skateman & @kangkyu Is minitest-rails going to support rails 7? It's been quite a while since rails 7 released and I haven't seen any movement with this Gem. It's the last item I have on a project before I can move it to Rails 7.

**Comment by taq** [comment]
> @skateman & @kangkyu Is minitest-rails going to support rails 7? It's been quite a while since rails 7 released and I haven't seen any movement with this Gem. It's the last item I have on a project before I can move it to Rails 7.

I made a fork and applied the patches to make a new Rails 7 app. :-(

**Comment by mateuszgorniak** [comment]
Can we merge existing PR and prevent next changes like this pining to very specific patch version of dependencies in the future? 🥺

**Comment by taq** [comment]
I'm trying to find who has write access to this repository, but Github is failing to even list all the contributors.

**Comment by taq** [comment]
Can someone living on US call Mike and ask if everything is ok? 801.541.8810

**Comment by grosser** [comment]
see https://github.com/blowmage/minitest-rails/pull/239

```
gem 'minitest-rails', git: 'https://github.com/grosser/minitest-rails', branch: "grosser/minor" # https://github.com/blowmage/minitest-rails/pull/239
```

**Comment by taq** [comment]
@grosser I made a fork also, but would love to keep this package here running ...

**Comment by grosser** [comment]
ah https://github.com/blowmage/minitest-rails/pull/236 is the same PR ... did not see that
@blowmage 👋

**Comment by grosser** [comment]
send an sms too
